[package]
name = "minecraft_bevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.0"
bevy_atmosphere = "0.7.0"
bevy_meshem = "0.2.1"
futures-lite = "1.13.0"
noise = "0.8.2"
